schema-version: v2
kind: plugin
metadata:
  name: stackspot-ci-pipeline-maven-plugin
  display-name: CI Pipeline plugin
  description: Habilita suporte a pipeline de CI com Github Actions
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  repository: https://github.com/leodelmiro/stackspot-ci-pipeline-maven-plugin
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
    - Kotlin
    - Java
    - Maven
  stk-projects-only: false
  inputs:
    - label: Qual a versão do Java utilizada pela aplicação?
      name: project_java_version
      type: text
      items:
        - "17"
        - "21"
      default: 17
      required: true
      help: 'Informe a versão do Java utilizada ou compatível com a aplicação'